// Code generated by "stringer -type=TOpCode"; DO NOT EDIT.

package ptool

import "strconv"

const _TOpCode_name = "ERRORNOPLABELENDJMPJZJNZCALLRETTRUEFALSEMARKRESTORERELEASEREPEATACCEPTPUSHNODEPOPNODECHECKRUNECHECKRANGECHECKSTRMAXINSTRUCTION"

var _TOpCode_index = [...]uint8{0, 5, 8, 13, 16, 19, 21, 24, 28, 31, 35, 40, 44, 51, 58, 64, 70, 78, 85, 94, 104, 112, 126}

func (i TOpCode) String() string {
	if i < 0 || i >= TOpCode(len(_TOpCode_index)-1) {
		return "TOpCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TOpCode_name[_TOpCode_index[i]:_TOpCode_index[i+1]]
}
